--------------------------------------------------------
--  Arquivo criado - Quinta-feira-Julho-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DESTINO
--------------------------------------------------------

  CREATE TABLE "CARONAS"."DESTINO" 
   (	"ID_DESTINO" NUMBER(19,0), 
	"ENDERECO" VARCHAR2(400 CHAR), 
	"LATITUDE" NUMBER(19,2), 
	"LONGITUDE" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DIA_SEMANA
--------------------------------------------------------

  CREATE TABLE "CARONAS"."DIA_SEMANA" 
   (	"ID_DIA_SEMANA" NUMBER(19,2), 
	"NOME" VARCHAR2(25 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GRUPO
--------------------------------------------------------

  CREATE TABLE "CARONAS"."GRUPO" 
   (	"ID_GRUPO" NUMBER(19,0), 
	"NOME" VARCHAR2(200 CHAR), 
	"ID_ROTINA" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTIFICACAO
--------------------------------------------------------

  CREATE TABLE "CARONAS"."NOTIFICACAO" 
   (	"ID_NOTIFICACAO" NUMBER(19,0), 
	"CONTEUDO" VARCHAR2(200 CHAR), 
	"ID_USUARIO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORIGEM
--------------------------------------------------------

  CREATE TABLE "CARONAS"."ORIGEM" 
   (	"ID_ORIGEM" NUMBER(19,0), 
	"ENDERECO" VARCHAR2(400 CHAR), 
	"LATITUDE" NUMBER(19,2), 
	"LONGITUDE" NUMBER(19,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROTINA
--------------------------------------------------------

  CREATE TABLE "CARONAS"."ROTINA" 
   (	"ID_ROTINA" NUMBER(19,0), 
	"DISTANCIA" NUMBER(19,2), 
	"DURACAO" NUMBER(19,2), 
	"HORARIO" TIMESTAMP (6), 
	"PASSAGEIRO" NUMBER(1,0), 
	"ID_DESTINO" NUMBER(19,0), 
	"ID_ORIGEM" NUMBER(19,0), 
	"ID_USUARIO" NUMBER(19,0), 
	"DISPONIVEL" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROTINA_DIA_SEMANA
--------------------------------------------------------

  CREATE TABLE "CARONAS"."ROTINA_DIA_SEMANA" 
   (	"ID_ROTINA_DIA_SEMANA" NUMBER(19,0), 
	"VAGAS_DISPONIVEIS" NUMBER(10,0), 
	"ID_DIA_SEMANA" NUMBER(19,2), 
	"ID_ROTINA" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SOLICITACAO
--------------------------------------------------------

  CREATE TABLE "CARONAS"."SOLICITACAO" 
   (	"ID_SOLICITACAO" NUMBER(19,0), 
	"ID_USUARIO_ALVO" NUMBER(19,0), 
	"ID_USUARIO_DONO" NUMBER(19,0), 
	"ID_ROTINA_USUARIO_DONO" NUMBER(19,0), 
	"ID_ROTINA_USUARIO_ALVO" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "CARONAS"."USUARIO" 
   (	"ID_USUARIO" NUMBER(19,0), 
	"EMAIL" VARCHAR2(200 CHAR), 
	"GENERO" VARCHAR2(25 CHAR), 
	"ID_AUTORIZACAO" VARCHAR2(1000 BYTE), 
	"NOME" VARCHAR2(200 CHAR), 
	"SENHA" VARCHAR2(1000 BYTE), 
	"URL_FOTO" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIO_GRUPO
--------------------------------------------------------

  CREATE TABLE "CARONAS"."USUARIO_GRUPO" 
   (	"ID_USUARIO_GRUPO" NUMBER(19,0), 
	"ID_GRUPO" NUMBER(19,0), 
	"ID_USUARIO" NUMBER(19,0), 
	"DATA_ENTRADA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DESTINO
--------------------------------------------------------

   CREATE SEQUENCE  "CARONAS"."SEQ_DESTINO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DIASEMANA
--------------------------------------------------------

   CREATE SEQUENCE  "CARONAS"."SEQ_DIASEMANA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_GRUPO
--------------------------------------------------------

   CREATE SEQUENCE  "CARONAS"."SEQ_GRUPO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_NOTIFICACAO
--------------------------------------------------------

   CREATE SEQUENCE  "CARONAS"."SEQ_NOTIFICACAO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ORIGEM
--------------------------------------------------------

   CREATE SEQUENCE  "CARONAS"."SEQ_ORIGEM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ROTINA
--------------------------------------------------------

   CREATE SEQUENCE  "CARONAS"."SEQ_ROTINA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ROTINADIASEMANA
--------------------------------------------------------

   CREATE SEQUENCE  "CARONAS"."SEQ_ROTINADIASEMANA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ROTINAGRUPO
--------------------------------------------------------

   CREATE SEQUENCE  "CARONAS"."SEQ_ROTINAGRUPO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SOLICITACAO
--------------------------------------------------------

   CREATE SEQUENCE  "CARONAS"."SEQ_SOLICITACAO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "CARONAS"."SEQ_USUARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USUARIOGRUPO
--------------------------------------------------------

   CREATE SEQUENCE  "CARONAS"."SEQ_USUARIOGRUPO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 2 NOORDER  NOCYCLE ;
REM INSERTING into CARONAS.DESTINO
SET DEFINE OFF;
REM INSERTING into CARONAS.DIA_SEMANA
SET DEFINE OFF;
REM INSERTING into CARONAS.GRUPO
SET DEFINE OFF;
REM INSERTING into CARONAS.NOTIFICACAO
SET DEFINE OFF;
REM INSERTING into CARONAS.ORIGEM
SET DEFINE OFF;
REM INSERTING into CARONAS.ROTINA
SET DEFINE OFF;
REM INSERTING into CARONAS.ROTINA_DIA_SEMANA
SET DEFINE OFF;
REM INSERTING into CARONAS.SOLICITACAO
SET DEFINE OFF;
REM INSERTING into CARONAS.USUARIO
SET DEFINE OFF;
REM INSERTING into CARONAS.USUARIO_GRUPO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index IX_GRUPO_ROTINA
--------------------------------------------------------

  CREATE INDEX "CARONAS"."IX_GRUPO_ROTINA" ON "CARONAS"."GRUPO" ("ID_ROTINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_ROTINA_USUARIO
--------------------------------------------------------

  CREATE INDEX "CARONAS"."IX_ROTINA_USUARIO" ON "CARONAS"."ROTINA" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_USUARIO_GRUPO_GRUPO
--------------------------------------------------------

  CREATE INDEX "CARONAS"."IX_USUARIO_GRUPO_GRUPO" ON "CARONAS"."USUARIO_GRUPO" ("ID_GRUPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_ROTINA_DIA_SEMANA_ROTINA
--------------------------------------------------------

  CREATE INDEX "CARONAS"."IX_ROTINA_DIA_SEMANA_ROTINA" ON "CARONAS"."ROTINA_DIA_SEMANA" ("ID_ROTINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_SOLICITACAO_ROTINA_ALVO
--------------------------------------------------------

  CREATE INDEX "CARONAS"."IX_SOLICITACAO_ROTINA_ALVO" ON "CARONAS"."SOLICITACAO" ("ID_ROTINA_USUARIO_ALVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_ROTINA_ORIGEM
--------------------------------------------------------

  CREATE INDEX "CARONAS"."IX_ROTINA_ORIGEM" ON "CARONAS"."ROTINA" ("ID_ORIGEM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_SOLICITACAO_ROTINA_DONO
--------------------------------------------------------

  CREATE INDEX "CARONAS"."IX_SOLICITACAO_ROTINA_DONO" ON "CARONAS"."SOLICITACAO" ("ID_ROTINA_USUARIO_DONO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_ROTINA_DESTINO
--------------------------------------------------------

  CREATE INDEX "CARONAS"."IX_ROTINA_DESTINO" ON "CARONAS"."ROTINA" ("ID_DESTINO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_ROTINA_DIA_SEMANA
--------------------------------------------------------

  CREATE INDEX "CARONAS"."IX_ROTINA_DIA_SEMANA" ON "CARONAS"."ROTINA_DIA_SEMANA" ("ID_DIA_SEMANA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_SOLICITACAO_USUARIO_ALVO
--------------------------------------------------------

  CREATE INDEX "CARONAS"."IX_SOLICITACAO_USUARIO_ALVO" ON "CARONAS"."SOLICITACAO" ("ID_USUARIO_ALVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_SOLICITACAO_USUARIO_DONO
--------------------------------------------------------

  CREATE INDEX "CARONAS"."IX_SOLICITACAO_USUARIO_DONO" ON "CARONAS"."SOLICITACAO" ("ID_USUARIO_DONO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_USUARIO_GRUPO_USUARIO
--------------------------------------------------------

  CREATE INDEX "CARONAS"."IX_USUARIO_GRUPO_USUARIO" ON "CARONAS"."USUARIO_GRUPO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IX_NOTIFICACAO_USUARIO
--------------------------------------------------------

  CREATE INDEX "CARONAS"."IX_NOTIFICACAO_USUARIO" ON "CARONAS"."NOTIFICACAO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "CARONAS"."USUARIO" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARONAS"."USUARIO" MODIFY ("SENHA" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."USUARIO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."USUARIO" MODIFY ("ID_AUTORIZACAO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROTINA_DIA_SEMANA
--------------------------------------------------------

  ALTER TABLE "CARONAS"."ROTINA_DIA_SEMANA" ADD PRIMARY KEY ("ID_ROTINA_DIA_SEMANA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARONAS"."ROTINA_DIA_SEMANA" MODIFY ("ID_ROTINA" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."ROTINA_DIA_SEMANA" MODIFY ("ID_DIA_SEMANA" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."ROTINA_DIA_SEMANA" MODIFY ("ID_ROTINA_DIA_SEMANA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO_GRUPO
--------------------------------------------------------

  ALTER TABLE "CARONAS"."USUARIO_GRUPO" ADD PRIMARY KEY ("ID_USUARIO_GRUPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARONAS"."USUARIO_GRUPO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."USUARIO_GRUPO" MODIFY ("ID_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."USUARIO_GRUPO" MODIFY ("ID_USUARIO_GRUPO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."USUARIO_GRUPO" MODIFY ("DATA_ENTRADA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICACAO
--------------------------------------------------------

  ALTER TABLE "CARONAS"."NOTIFICACAO" MODIFY ("ID_NOTIFICACAO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."NOTIFICACAO" MODIFY ("CONTEUDO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."NOTIFICACAO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."NOTIFICACAO" ADD PRIMARY KEY ("ID_NOTIFICACAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SOLICITACAO
--------------------------------------------------------

  ALTER TABLE "CARONAS"."SOLICITACAO" ADD PRIMARY KEY ("ID_SOLICITACAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARONAS"."SOLICITACAO" MODIFY ("ID_USUARIO_DONO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."SOLICITACAO" MODIFY ("ID_USUARIO_ALVO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."SOLICITACAO" MODIFY ("ID_SOLICITACAO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."SOLICITACAO" MODIFY ("ID_ROTINA_USUARIO_ALVO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."SOLICITACAO" MODIFY ("ID_ROTINA_USUARIO_DONO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRUPO
--------------------------------------------------------

  ALTER TABLE "CARONAS"."GRUPO" ADD PRIMARY KEY ("ID_GRUPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARONAS"."GRUPO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."GRUPO" MODIFY ("ID_GRUPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROTINA
--------------------------------------------------------

  ALTER TABLE "CARONAS"."ROTINA" ADD PRIMARY KEY ("ID_ROTINA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARONAS"."ROTINA" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."ROTINA" MODIFY ("ID_ORIGEM" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."ROTINA" MODIFY ("ID_DESTINO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."ROTINA" MODIFY ("PASSAGEIRO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."ROTINA" MODIFY ("HORARIO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."ROTINA" MODIFY ("DURACAO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."ROTINA" MODIFY ("DISTANCIA" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."ROTINA" MODIFY ("ID_ROTINA" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."ROTINA" ADD CONSTRAINT "UK_DESTINO" UNIQUE ("ID_DESTINO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARONAS"."ROTINA" ADD CONSTRAINT "UK_ORIGEM" UNIQUE ("ID_ORIGEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARONAS"."ROTINA" MODIFY ("DISPONIVEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORIGEM
--------------------------------------------------------

  ALTER TABLE "CARONAS"."ORIGEM" ADD PRIMARY KEY ("ID_ORIGEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARONAS"."ORIGEM" MODIFY ("LONGITUDE" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."ORIGEM" MODIFY ("LATITUDE" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."ORIGEM" MODIFY ("ENDERECO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."ORIGEM" MODIFY ("ID_ORIGEM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DIA_SEMANA
--------------------------------------------------------

  ALTER TABLE "CARONAS"."DIA_SEMANA" ADD PRIMARY KEY ("ID_DIA_SEMANA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARONAS"."DIA_SEMANA" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."DIA_SEMANA" MODIFY ("ID_DIA_SEMANA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DESTINO
--------------------------------------------------------

  ALTER TABLE "CARONAS"."DESTINO" ADD PRIMARY KEY ("ID_DESTINO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CARONAS"."DESTINO" MODIFY ("LONGITUDE" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."DESTINO" MODIFY ("LATITUDE" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."DESTINO" MODIFY ("ENDERECO" NOT NULL ENABLE);
  ALTER TABLE "CARONAS"."DESTINO" MODIFY ("ID_DESTINO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GRUPO
--------------------------------------------------------

  ALTER TABLE "CARONAS"."GRUPO" ADD CONSTRAINT "FK_GRUPO_ROTINA" FOREIGN KEY ("ID_ROTINA")
	  REFERENCES "CARONAS"."ROTINA" ("ID_ROTINA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICACAO
--------------------------------------------------------

  ALTER TABLE "CARONAS"."NOTIFICACAO" ADD CONSTRAINT "FK_NOTIFICACAO_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "CARONAS"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROTINA
--------------------------------------------------------

  ALTER TABLE "CARONAS"."ROTINA" ADD CONSTRAINT "FK_ROTINA_DESTINO" FOREIGN KEY ("ID_DESTINO")
	  REFERENCES "CARONAS"."DESTINO" ("ID_DESTINO") ENABLE;
  ALTER TABLE "CARONAS"."ROTINA" ADD CONSTRAINT "FK_ROTINA_ORIGEM" FOREIGN KEY ("ID_ORIGEM")
	  REFERENCES "CARONAS"."ORIGEM" ("ID_ORIGEM") ENABLE;
  ALTER TABLE "CARONAS"."ROTINA" ADD CONSTRAINT "FK_ROTINA_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "CARONAS"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ROTINA_DIA_SEMANA
--------------------------------------------------------

  ALTER TABLE "CARONAS"."ROTINA_DIA_SEMANA" ADD CONSTRAINT "FK_ROTINA_DIA_SEMANA" FOREIGN KEY ("ID_DIA_SEMANA")
	  REFERENCES "CARONAS"."DIA_SEMANA" ("ID_DIA_SEMANA") ENABLE;
  ALTER TABLE "CARONAS"."ROTINA_DIA_SEMANA" ADD CONSTRAINT "FK_ROTINA_DIA_SEMANA_ROTINA" FOREIGN KEY ("ID_ROTINA")
	  REFERENCES "CARONAS"."ROTINA" ("ID_ROTINA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SOLICITACAO
--------------------------------------------------------

  ALTER TABLE "CARONAS"."SOLICITACAO" ADD CONSTRAINT "FK_SOLICITACAO_ROTINA_ALVO" FOREIGN KEY ("ID_ROTINA_USUARIO_ALVO")
	  REFERENCES "CARONAS"."ROTINA" ("ID_ROTINA") ENABLE;
  ALTER TABLE "CARONAS"."SOLICITACAO" ADD CONSTRAINT "FK_SOLICITACAO_ROTINA_DONO" FOREIGN KEY ("ID_ROTINA_USUARIO_DONO")
	  REFERENCES "CARONAS"."ROTINA" ("ID_ROTINA") ENABLE;
  ALTER TABLE "CARONAS"."SOLICITACAO" ADD CONSTRAINT "FK_SOLICITACAO_USUARIO_ALVO" FOREIGN KEY ("ID_USUARIO_ALVO")
	  REFERENCES "CARONAS"."USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "CARONAS"."SOLICITACAO" ADD CONSTRAINT "FK_SOLICITACAO_USUARIO_DONO" FOREIGN KEY ("ID_USUARIO_DONO")
	  REFERENCES "CARONAS"."USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO_GRUPO
--------------------------------------------------------

  ALTER TABLE "CARONAS"."USUARIO_GRUPO" ADD CONSTRAINT "FK_USUARIO_GRUPO_GRUPO" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "CARONAS"."GRUPO" ("ID_GRUPO") ENABLE;
  ALTER TABLE "CARONAS"."USUARIO_GRUPO" ADD CONSTRAINT "FK_USUARIO_GRUPO_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "CARONAS"."USUARIO" ("ID_USUARIO") ENABLE;
